# configs/default.toml
# mode: direct | http_payload | sni_fronted

mode             = "http_payload"
proxy            = "your.proxy.host:80"    # host your ISP sees
target           = "your.target.host:80"   # SSH-over-WS server
ssh_username     = ""
ssh_password     = ""
local_socks_port = 1080
front_domain     = ""                      # sni_fronted only
udpgw = "127.0.0.1:7300"   # badvpn-udpgw on remote server, leave empty to disable

# [host] → target host:port  |  [crlf] → \r\n  |  [split] → block boundary
payload_template = "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]"